const INVENTORY_TRANSACTION_TYPE = Object.freeze({
  PURCHASE: "PURCHASE",
  SALE: "SALE",
  RETURN: "RETURN",
  ADJUSTMENT: "ADJUSTMENT",
  DAMAGE: "DAMAGE",
});


export default INVENTORY_TRANSACTION_TYPE;