const PURCHASE_ORDER_STATUS = Object.freeze({
  PENDING: "PENDING",
  PARTIALLY_RECEIVED: "PARTIALLY_RECEIVED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED"
});

export default PURCHASE_ORDER_STATUS;
